language: php
os: linux

services:
  - docker

jobs:
  fast_finish: true
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.1
      arch: s390x
    - php: 7.2
    - php: 7.2
      arch: s390x
    - php: 7.2
      arch: arm64
      env: ARCH=arm32
    - php: 7.3
    - php: 7.3
      arch: s390x
    - php: 7.3
      arch: arm64
      env: ARCH=arm32
    - php: 7.4
    - php: 7.4
      arch: s390x
    - php: 7.4
      arch: arm64
      env: ARCH=arm32
    - php: nightly
    - php: nightly
      arch: s390x
  allow_failures:
    - php: nightly

addons:
  apt:
    update: true
    packages:
      - bsdmainutils
      - libsodium-dev
      - uuid-dev

before_install:
  - travis_retry ./resources/scripts/travis-before-install.sh
  - ./resources/scripts/cmd-proxy.sh ./resources/scripts/system-info.sh

install:
  - travis_retry ./resources/scripts/cmd-proxy.sh composer require --no-update "php-coveralls/php-coveralls:^1 | ^2"
  - travis_retry ./resources/scripts/cmd-proxy.sh composer install --no-interaction --prefer-dist --no-progress --no-suggest

before_script:
  - mkdir -p build/logs

script:
  - ./resources/scripts/cmd-proxy.sh ./vendor/bin/parallel-lint src tests
  - ./resources/scripts/cmd-proxy.sh ./vendor/bin/phpcs src tests --standard=psr2 -sp --colors
  - travis_wait ./resources/scripts/cmd-proxy.sh ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry ./resources/scripts/php-coveralls.sh
